services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sacrascriptura
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Servicio principal de Ollama - corre Mistral 7B permanentemente para embeddings
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-main
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    deploy:
      resources:
        limits:
          memory: 10G  # Límite de memoria para no saturar el sistema
        reservations:
          memory: 4G   # Memoria garantizada mínima
    restart: unless-stopped
    entrypoint: ["ollama", "serve"]
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  postgres-data:
  ollama-data:
